// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title VibeProof - AI Smart Contract Security Auditor & Certification
 * @author VibeProof Team (Build Week Hackathon Vol.2)
 * @notice Verifiable security audit records deployed on BOT Chain
 * @dev Fully EVM-compatible with BOT Chain Testnet (ID 968) and Mainnet (ID 677)
 */
contract VibeProof {
    address public immutable owner;

    struct AuditRecord {
        bytes32 codeHash;        // keccak256 hash of the audited Solidity code
        string projectName;     // Name of the audited smart contract or project
        uint8 securityScore;    // Security safety score (0 - 100)
        string auditVerdict;    // "SAFE", "WARNING", or "CRITICAL"
        string reportSummary;   // Brief summary generated by AI Auditor
        address auditorWallet;  // Wallet address that requested & certified the audit
        uint256 timestamp;      // Block timestamp when certified on BOT Chain
        bool exists;
    }

    // Mapping from codeHash to AuditRecord
    mapping(bytes32 => AuditRecord) public audits;

    // Array of all audited code hashes for chronological retrieval
    bytes32[] public auditHashes;

    event AuditIssued(
        bytes32 indexed codeHash,
        string projectName,
        uint8 securityScore,
        string auditVerdict,
        address indexed auditorWallet,
        uint256 timestamp
    );

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Issue and permanently record a smart contract security audit certificate on BOT Chain
     * @param _codeHash The keccak256 hash of the audited contract source code
     * @param _projectName Human-readable name of the contract
     * @param _securityScore Calculated score between 0 and 100
     * @param _verdict Categorical verdict ("SAFE", "WARNING", "CRITICAL")
     * @param _reportSummary Summary of findings and recommendations
     */
    function certifyAudit(
        bytes32 _codeHash,
        string memory _projectName,
        uint8 _securityScore,
        string memory _verdict,
        string memory _reportSummary
    ) external {
        require(_codeHash != bytes32(0), "Invalid code hash");
        require(_securityScore <= 100, "Score must be 0-100");
        require(bytes(_projectName).length > 0, "Project name required");

        if (!audits[_codeHash].exists) {
            auditHashes.push(_codeHash);
        }

        audits[_codeHash] = AuditRecord({
            codeHash: _codeHash,
            projectName: _projectName,
            securityScore: _securityScore,
            auditVerdict: _verdict,
            reportSummary: _reportSummary,
            auditorWallet: msg.sender,
            timestamp: block.timestamp,
            exists: true
        });

        emit AuditIssued(
            _codeHash,
            _projectName,
            _securityScore,
            _verdict,
            msg.sender,
            block.timestamp
        );
    }

    /**
     * @notice Fetch an audit record by its code hash
     * @param _codeHash The hash of the audited source code
     */
    function getAudit(bytes32 _codeHash) external view returns (AuditRecord memory) {
        require(audits[_codeHash].exists, "Audit does not exist");
        return audits[_codeHash];
    }

    /**
     * @notice Check if a specific contract code hash has been audited
     * @param _codeHash The hash to check
     */
    function isCodeCertified(bytes32 _codeHash) external view returns (bool) {
        return audits[_codeHash].exists;
    }

    /**
     * @notice Get total count of certified audits on BOT Chain
     */
    function getTotalAudits() external view returns (uint256) {
        return auditHashes.length;
    }

    /**
     * @notice Retrieve the latest audit records (up to limit)
     * @param limit Maximum number of records to return
     */
    function getLatestAudits(uint256 limit) external view returns (AuditRecord[] memory) {
        uint256 total = auditHashes.length;
        if (total == 0) {
            return new AuditRecord[](0);
        }

        uint256 returnCount = limit > total ? total : limit;
        AuditRecord[] memory records = new AuditRecord[](returnCount);

        for (uint256 i = 0; i < returnCount; i++) {
            bytes32 hash = auditHashes[total - 1 - i];
            records[i] = audits[hash];
        }

        return records;
    }
}
